// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package com.apollographql.apollo.sample.type;

/**
 * A list of options for the sort order of the feed
 */
public enum FeedType {
  /**
   * Sort by a combination of freshness and score, using Reddit's algorithm
   */
  HOT("HOT"),

  /**
   * Newest entries first
   */
  NEW("NEW"),

  /**
   * Highest score entries first
   */
  TOP("TOP"),

  /**
   * Auto generated constant for unknown enum values
   */
  $UNKNOWN("$UNKNOWN");

  private final String rawValue;

  FeedType(String rawValue) {
    this.rawValue = rawValue;
  }

  public String rawValue() {
    return rawValue;
  }

  public static FeedType safeValueOf(String rawValue) {
    for (FeedType enumValue : values()) {
      if (enumValue.rawValue.equals(rawValue)) {
        return enumValue;
      }
    }
    return FeedType.$UNKNOWN;
  }
}
